AppBundle\Entity\User:
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'
        delete:
            method: 'DELETE'
        user_postman_collection_item:
            route_name: 'api_users_postman_collections_get_item'
        user_postman_environment_item:
            route_name: 'api_users_postman_environments_get_item'
        user_postman_collection_list:
            route_name: 'api_users_postman_collections_get_collection'
        user_postman_environment_list:
            route_name: 'api_users_postman_environments_get_collection'
    collectionOperations:
        get:
            method: 'GET'
        post:
            method: 'POST'
