AppBundle\Entity\User:
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'
        delete:
            method: 'DELETE'
        user_postman_sync:
            route_name: 'api_users_postman_sync'
    collectionOperations:
        get:
            method: 'GET'
        post:
            method: 'POST'
