ui:
    resource: "@UiBundle/Controller/"
    type:     'annotation'
    prefix:   '/ui'

api:
    resource: '.'
    type: 'api_platform'
    prefix: '/'

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: '/login_check'